var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                   xxxx                                                         ",
   "                   x!!x                                                         ",
   "                   xxvx               o o      xx                               ",
   "                                    xxxxxx                                      ",
   "                                                               xx               ",
   "                                              o                                 ",
   "  xx                                        xxxxx                               ",
   "  x                     o                                                       ",
   "  x                                       o                   o         o xx    ",
   "  x      e   xxxxxx                    x  xxx                 xxx                ",
   "  x  @       x  x       o   x         x          x      e            xxxxxx      ",
   "  xxxxxxxxxxxx  xxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxx  ",
   "                    x!x                          x     x                        ",
   "                    xxx                          x!!!!!x                        ",
   "                                                 x!!!!!x                        ",
   "                                                 xxxxxxx                        ",
   "                                                                                "],
  ["                                                                                                      ",
   "                                                                                                      ",
   "                                                                                                      ",
   "                                                                                                      ",
   "                                                                                                      ",
   "                                                                                                      ",
   "                                                                                                      ",
   "    xxxx                                                                                              ", 
   "    x!!x                                                                   x!!!!x                     ",
   "    xvxx                                          xxxxxxxxxx               x=   x                     ",
   "                  xx                     xxx      x!!!!!xxxxxxxxxxxx       xxxxxx                     ",
   "                                   o              x!!!!!!!!!!!!!!!xx e    e                           ",
   "                               o  xxxx            x!!!!!xxxxxxxxxxxx                                  ",
   "                  o                               xxxxxxxx                                            ",
   "                  o    xx       xxxx      xxx                                                         ",
   "                  x        x                                o   o      x                              ",
   "               xxxxxxx    xxxx                                                    xx                  ",
   "              xx     x=   x       xxx                       xxxxxx                                    ",
   "            xx       x!!!!x       x!x              xxxxxx              xx         o      xxx           ",
   "          xx  x       x           xxx                                                                 ",
   "    xxx @     x e      x                       xxxx         xx      x   xxxxx   xxxxxx                ",
   "    x xxxxxxx       x           x                x    xx                                             ",
   "xxxxx x         xxxxxx       xxx        xx!!!!!!!x     x          xxx      e         xxx              ",
   "xxxxx x!!!!!!x        xxx =  xx   xxx   xxxxxxxxxx    xxx!!!!!!!xx       xxxxxxxxxxxx xxxx           ",
   "xxxxx x!!!!!!x         xxxxxxx                                   x=       x                            ",
   "xxxxx x!!!!!!x                                                   xxxxxxxxx                            ",
   "xxxxx x!!!!!!x                                                                                        ",
   "xxxxx x!!!!!!x                                                                                        ",
   "      x!!!!!!x                                                                                        "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                             ",
   "                                                                                                             ",
   "                                                                                                             ",
   "                                                                                                             ",
   "                                                                                                             ",
   "                                                                                                             ",
   "                                                                                                             ",
   "                                                             xxx                                             ",
   "                                                             x!x                                             ",
   "                                                             xvx                                             ",
   "                                                                                                             ",
   "               xxxxx                                                                                         ",
   "               x!!!x                                          v                                              ",
   "               xxvxx                                                                                         ",
   "                                                                                                             ",
   "                                                                                                             ",
   "                                                                                                             ",
   "                 v                                                                                           ",
   "                                                                                                             ",
   "                                                                                                             ",
   "                                                                                                             ",
   "                                                                                                             ",
   "                     xxxxxxxx                        xxxxxxxxxxxxx                                                        ",
   "                     x!!!!!!x                        x!!!xx!!!!!xx                                                     ",
   "                     x!!!!!!xe                       x !!!!!!!!!!x                                                        ",
   "                     x!!!!!!x                        x   !!!!!!!!x                                                     ",
   "      @              x!!!!!!x                        xx     =   xx                                              ",
   "     xxx             xxxxxxxx                                                                xxx            ",
   "     x x                                                                      x!!!x                xxx       ",
   "     x x                                 xx                                    xxx                 x x       ",
   "     x x                           xxxxxxxx                        xxxxx                             x       ",
   "     x x                        o                                        x   x                               ",
   "     x x              o   x     xxx          xxx    o                          x x x                          ",
   "     x x                                          xxx                                                        ",
   "     x x  o          xx             o                             x                 xxx                      ",
   "     x x   xx                  xxx          x                  o      xx    xxx       x!!!x          x       ",
   "     x x     x      o        e                                  x x          xxx          xxx        x       ",
   "     x x x          xxxxx    xxxxxxxxxxxxx= x =  x!!!!x     x =  x    x     xx xx                    xxx     ",
   "     x x         o           x           x!!x    x!!!!x =   x!!!!x    xx    xx                    x      x   ",
   "  xxxxxxxxxxxx xxxxxxxxxxxxxxx           xxxxxxxxx!!!xx    xxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "             x!x                                 x!!!x                                                       ",
   "             x!x                                 x!!!x                                                       ",
   "											     xxxxx														 "],
   ];


if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
  
  
